# Generated by Django 5.0.2 on 2024-03-02 20:23

import example_app.fields
import example_app.pd_models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('details', example_app.fields.PydanticJSONField(pydantic_model=example_app.pd_models.SampleProduct)),
            ],
        ),
    ]
